; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{72605806-6295-4F60-B9BF-B4E0F36F1EB3}
AppName=Preguntados
AppVersion=1.0
;AppVerName=Preguntados 1.0
AppPublisher=aaaaa
DefaultDirName=C:\Preguntados
DefaultGroupName=Preguntados
OutputDir=C:\Users\Usuario\OneDrive\Desktop
OutputBaseFilename=setup_preguntados
SetupIconFile=C:\Users\Usuario\source\repos\proyectofinalbeta11\draft1proyectoPrograIV\draft1proyectoPrograIV\Recursos\PREGUNTADOS.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\Users\Usuario\source\repos\ProyectoFinalBeta13\draft1proyectoPrograIV\draft1proyectoPrograIV\bin\Debug\draft1proyectoPrograIV.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Usuario\source\repos\ProyectoFinalBeta13\draft1proyectoPrograIV\draft1proyectoPrograIV\bin\Debug\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Preguntados"; Filename: "{app}\draft1proyectoPrograIV.exe"
Name: "{group}\{cm:UninstallProgram,Preguntados}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\Preguntados"; Filename: "{app}\draft1proyectoPrograIV.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\Preguntados"; Filename: "{app}\draft1proyectoPrograIV.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\draft1proyectoPrograIV.exe"; Description: "{cm:LaunchProgram,Preguntados}"; Flags: nowait postinstall skipifsilent

