; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0E6B92A1-83A2-4AFB-AD1E-064636D7D4FE}
AppName=Preguntados
AppVersion=1.0
;AppVerName=Preguntados 1.0
AppPublisher=Minor Porras
DefaultDirName=C:\Users\Usuario\source\repos\proyectofinalbeta11\Preguntados
DefaultGroupName=Preguntados
OutputBaseFilename=setup
SetupIconFile=C:\Users\Usuario\source\repos\proyectofinalbeta11\draft1proyectoPrograIV\draft1proyectoPrograIV\Recursos\PREGUNTADOS.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Usuario\source\repos\ProyectoFinalBeta13\draft1proyectoPrograIV\draft1proyectoPrograIV\bin\Debug\draft1proyectoPrograIV.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Usuario\source\repos\ProyectoFinalBeta13\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Preguntados"; Filename: "{app}\draft1proyectoPrograIV.exe"
Name: "{group}\{cm:UninstallProgram,Preguntados}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\Preguntados"; Filename: "{app}\draft1proyectoPrograIV.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\draft1proyectoPrograIV.exe"; Description: "{cm:LaunchProgram,Preguntados}"; Flags: nowait postinstall skipifsilent

